/**
 * Replaces the `movies` suggest collection with 80 picks — 20 per filter chip —
 * each linking to its IMDb page. Run once with `bun run seed:movies`.
 * Replacing the collection (and what that deletes) is handled by
 * ./replace-suggest-collection.
 *
 * No film appears twice: a card carries one group, so a title placed in two
 * chips would have to be two rows pointing at the same IMDb page.
 *
 * Every card carries a `group`, which is what the collection page turns into
 * its filter chips — it builds them from the distinct values its own cards
 * carry, so these four strings are the whole definition of the four buttons.
 * They have to match exactly to merge into one chip; a typo silently makes a
 * fifth. Order here is order there, since the page keeps the order the API
 * returned.
 *
 * Art is TMDB's landscape backdrop, not the portrait poster: the card is wide,
 * and a poster dropped into it would be cropped to a strip of somebody's chin.
 * Hotlinked from TMDB's image CDN, which serves these without an API key —
 * imgUrl() passes an absolute http(s) URL straight through (see
 * components/bigbang/data.ts). Only the lookup needed a key, and that ran once,
 * offline, while writing this file: no key is stored in this repo or read at
 * seed time.
 *
 * Titles carry their year because several of these have same-named films or
 * remakes, and the year is the quickest way to see which one a card means.
 */
import { prisma } from '../lib/prisma';
import { replaceSuggestCollection, type SuggestItem } from './replace-suggest-collection';

const COLLECTION_SLUG = 'movies';

const imdb = (id: string) => `https://www.imdb.com/title/${id}/`;

const MOVIES: SuggestItem[] = [
  {
    name: 'La La Land (2016)',
    group: 'Хосоороо үзэх',
    description: 'Лос-Анжелесийн мөрөөдөл ба хайрын хооронд сонголт хийх хоёр — өнгө, хөгжмөөрөө өөрөө нэг үзэсгэлэн',
    link: imdb('tt3783958'),
    image: 'https://image.tmdb.org/t/p/w1280/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg',
  },
  {
    name: 'Eternal Sunshine of the Spotless Mind (2004)',
    group: 'Хосоороо үзэх',
    description: 'Бие биенээ дурсамжаасаа устгасан хос — устгаж дуусахаас өмнө эргэж бодох тухай',
    link: imdb('tt0338013'),
    image: 'https://image.tmdb.org/t/p/w1280/W1ffLQGHoxfAOq0ZYdPtJlvAdb.jpg',
  },
  {
    name: 'Before Sunrise (1995)',
    group: 'Хосоороо үзэх',
    description: 'Венад буусан хоёр танихгүй хүн, нэг шөнийн яриа. Ярилцах дуртай хосуудад',
    link: imdb('tt0112471'),
    image: 'https://image.tmdb.org/t/p/w1280/qA2TyqPldTtoTVY3LKrNIG5g6bH.jpg',
  },
  {
    name: 'Before Sunset (2004)',
    group: 'Хосоороо үзэх',
    description: 'Есөн жилийн дараа Парист дахин уулзсан тэр хоёр — үргэлжлэл нь эх хувилбартаа хүрнэ',
    link: imdb('tt0381681'),
    image: 'https://image.tmdb.org/t/p/w1280/tcZi0LQc5iu2u6i5aOWyj9NBBvl.jpg',
  },
  {
    name: 'Past Lives (2023)',
    group: 'Хосоороо үзэх',
    description: 'Хорин жилийн дараа уулзсан хоёр — юу ч болоогүй, гэсэн ч бүх зүйл болсон',
    link: imdb('tt13238346'),
    image: 'https://image.tmdb.org/t/p/w1280/7HR38hMBl23lf38MAN63y4pKsHz.jpg',
  },
  {
    name: '(500) Days of Summer (2009)',
    group: 'Хосоороо үзэх',
    description: 'Хайрын түүхийг эхнээс нь биш, холилдуулж ярьсан — бүх зүйл сайхан төгсдөггүй',
    link: imdb('tt1022603'),
    image: 'https://image.tmdb.org/t/p/w1280/1M2i4Mxd03elGOTmEkIvqrHfmyS.jpg',
  },
  {
    name: 'Amélie (2001)',
    group: 'Хосоороо үзэх',
    description: 'Парисын хачирхалтай сайхан ертөнц, бусдын амьдралыг өөрчилдөг охин',
    link: imdb('tt0211915'),
    image: 'https://image.tmdb.org/t/p/w1280/6n53UI4mX9QMfe2S0Pgt8mGebY1.jpg',
  },
  {
    name: 'Pride & Prejudice (2005)',
    group: 'Хосоороо үзэх',
    description: 'Остений сонгодог — дүрс, хөгжим нь өөрсдөө үнэ цэнэтэй',
    link: imdb('tt0414387'),
    image: 'https://image.tmdb.org/t/p/w1280/1Onam6oWyFAUCcoxtdWkACtEiNr.jpg',
  },
  {
    name: 'Her (2013)',
    group: 'Хосоороо үзэх',
    description: 'Хиймэл оюунд дурласан эр — ганцаардлын тухай гунигтай сайхан кино',
    link: imdb('tt1798709'),
    image: 'https://image.tmdb.org/t/p/w1280/sPPsR9f4K0movWVQ99u4uMqFzEL.jpg',
  },
  {
    name: 'Call Me by Your Name (2017)',
    group: 'Хосоороо үзэх',
    description: 'Италийн зун, анхны хайр, түүнийг дагасан өвдөлт',
    link: imdb('tt5726616'),
    image: 'https://image.tmdb.org/t/p/w1280/4Xh2a1WeTp6b8Ksvug0pAMbX3dT.jpg',
  },
  {
    name: 'The Notebook (2004)',
    group: 'Хосоороо үзэх',
    description: 'Сонгодог мелодрам — нулимс бэлдээрэй',
    link: imdb('tt0332280'),
    image: 'https://image.tmdb.org/t/p/w1280/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg',
  },
  {
    name: 'Me Before You (2016)',
    group: 'Хосоороо үзэх',
    description: 'Асрагч охин, тэргэнцэрт залуу — хөнгөн эхэлж, хүндээр төгсдөг',
    link: imdb('tt2674426'),
    image: 'https://image.tmdb.org/t/p/w1280/3WK7p9EdZmmvB1IbB2Vw9Rf4lXH.jpg',
  },
  {
    name: 'Silver Linings Playbook (2012)',
    group: 'Хосоороо үзэх',
    description: 'Хоёр эмзэг хүн бүжгийн тэмцээнээр дамжин эдгэрэх нь',
    link: imdb('tt1045658'),
    image: 'https://image.tmdb.org/t/p/w1280/12GpsUm9nVVKFlcjDTflKLClFVA.jpg',
  },
  {
    name: 'Crazy, Stupid, Love. (2011)',
    group: 'Хосоороо үзэх',
    description: 'Салсан эр дахин болзож сурах гэж оролдоно — ухаалаг ромком',
    link: imdb('tt1570728'),
    image: 'https://image.tmdb.org/t/p/w1280/vyrCniZsrXZAW08eECKIp1BMLPh.jpg',
  },
  {
    name: '10 Things I Hate About You (1999)',
    group: 'Хосоороо үзэх',
    description: 'Шекспирийг ахлах сургууль руу зөөсөн ерээд оны сонгодог',
    link: imdb('tt0147800'),
    image: 'https://image.tmdb.org/t/p/w1280/yvPbncYhMu9FfTjDhq0N5lgnVkO.jpg',
  },
  {
    name: 'Lost in Translation (2003)',
    group: 'Хосоороо үзэх',
    description: 'Токиогийн зочид буудалд учирсан хоёр нойргүй хүн',
    link: imdb('tt0335266'),
    image: 'https://image.tmdb.org/t/p/w1280/6ITVHoipvxAS8luzKtHTbPaHLtT.jpg',
  },
  {
    name: 'Midnight in Paris (2011)',
    group: 'Хосоороо үзэх',
    description: 'Шөнө дунд болгонд хорьдугаад оны Парис руу нүүдэг зохиолч',
    link: imdb('tt1605783'),
    image: 'https://image.tmdb.org/t/p/w1280/b5bcKhvN6VP82U5ztNdPfOLiolD.jpg',
  },
  {
    name: 'The Shape of Water (2017)',
    group: 'Хосоороо үзэх',
    description: 'Хэл дүлий охин, усны амьтан — Дель Торогийн үлгэр',
    link: imdb('tt5580390'),
    image: 'https://image.tmdb.org/t/p/w1280/abirSHwWgKajV3hXhaIR5lcCIXe.jpg',
  },
  {
    name: 'Notting Hill (1999)',
    group: 'Хосоороо үзэх',
    description: 'Лондонгийн номын дэлгүүрийн эзэн Холливүүдийн одтой учрах нь',
    link: imdb('tt0125439'),
    image: 'https://image.tmdb.org/t/p/w1280/enTZhfxAdgOCdFdbj52MR3F10yC.jpg',
  },
  {
    name: 'A Star Is Born (2018)',
    group: 'Хосоороо үзэх',
    description: 'Нэг од мандаж, нөгөө нь живэх тухай — хөгжим нь өөрөө гол дүр',
    link: imdb('tt1517451'),
    image: 'https://image.tmdb.org/t/p/w1280/dDYpjrwh1wNVQk0rEpc9P81wQt4.jpg',
  },
  {
    name: 'About Time (2013)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Цаг хугацаа буцаах чадвартай залуу — гэхдээ кино нь эцэстээ хайр биш, гэр бүлийн тухай',
    link: imdb('tt2194499'),
    image: 'https://image.tmdb.org/t/p/w1280/einbto9qLXFx9QXxEHylaxDbKPx.jpg',
  },
  {
    name: 'Your Name. (2016)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Биеэ сольсон хоёр өсвөр насны хүүхэд — анимэ үздэггүй хүнийг ч татдаг',
    link: imdb('tt5311514'),
    image: 'https://image.tmdb.org/t/p/w1280/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  },
  {
    name: 'The Princess Bride (1987)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Үлгэр, илд, инээдэм, элэглэл бүгд нэг дор. Хамгийн хөнгөн сонголт',
    link: imdb('tt0093779'),
    image: 'https://image.tmdb.org/t/p/w1280/2CisgvF2HcIVnbMZbSjASCtSgEb.jpg',
  },
  {
    name: 'Paddington 2 (2017)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Эелдэг баавгайн тухай — насанд хүрэгчид ч чин сэтгэлээсээ инээдэг ховор кино',
    link: imdb('tt4468740'),
    image: 'https://image.tmdb.org/t/p/w1280/kRVUMsXFzhuXjr20JcCGc6TapxA.jpg',
  },
  {
    name: 'Spirited Away (2001)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Миязакигийн шилдэг — сүнснүүдийн ертөнцөд төөрсөн охины аялал',
    link: imdb('tt0245429'),
    image: 'https://image.tmdb.org/t/p/w1280/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  },
  {
    name: 'Up (2009)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Эхний арван минут нь бүтэн кинонд хүрнэ. Бөмбөлгөөр нисэх өвгөний адал явдал',
    link: imdb('tt1049413'),
    image: 'https://image.tmdb.org/t/p/w1280/hGGC9gKo7CFE3fW07RA587e5kol.jpg',
  },
  {
    name: 'Inside Out (2015)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Толгой доторх сэтгэл хөдлөлүүд — хүүхдэд ойлгомжтой, том хүнд илүү хэрэгтэй',
    link: imdb('tt2096673'),
    image: 'https://image.tmdb.org/t/p/w1280/o3i6AfTcWAuNvzAUV3q5lOmi6Gx.jpg',
  },
  {
    name: 'Coco (2017)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Мексикийн үхэгсдийн баяр, гэр бүлийн дурсамж, хөгжим',
    link: imdb('tt2380307'),
    image: 'https://image.tmdb.org/t/p/w1280/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg',
  },
  {
    name: 'Finding Nemo (2003)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Хүүгээ хайж далай гатласан загас аав',
    link: imdb('tt0266543'),
    image: 'https://image.tmdb.org/t/p/w1280/eCynaAOgYYiw5yN5lBwz3IxqvaW.jpg',
  },
  {
    name: 'WALL·E (2008)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Хогтой дэлхийд үлдсэн ганц робот — эхний хагаст үг бараг байхгүй',
    link: imdb('tt0910970'),
    image: 'https://image.tmdb.org/t/p/w1280/nYs4ZwnJBK4AgljhvzwNz7fpr3E.jpg',
  },
  {
    name: 'Toy Story (1995)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Тоглоомууд амьд байдаг — Pixar-ын эхлэл',
    link: imdb('tt0114709'),
    image: 'https://image.tmdb.org/t/p/w1280/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg',
  },
  {
    name: 'Monsters, Inc. (2001)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Хүүхдийн хашгираанаар цахилгаан үйлдвэрлэдэг мангасын хот',
    link: imdb('tt0198781'),
    image: 'https://image.tmdb.org/t/p/w1280/sDTnMOJ3H5wI38OxObmCtK7wfd5.jpg',
  },
  {
    name: 'The Lion King (1994)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Симбагийн түүх. Тайлбар шаардахгүй',
    link: imdb('tt0110357'),
    image: 'https://image.tmdb.org/t/p/w1280/q00H8EqULYSK74lgevMkhmGGLHn.jpg',
  },
  {
    name: 'The Incredibles (2004)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Супер хүчтэй гэр бүл тэтгэвэрт гарсан нь',
    link: imdb('tt0317705'),
    image: 'https://image.tmdb.org/t/p/w1280/lxwzY9vNwjDgxWKt3zZ6zcU6rEJ.jpg',
  },
  {
    name: 'Ratatouille (2007)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Тогооч болохыг мөрөөдсөн хулгана, Парисын гал тогоо',
    link: imdb('tt0382932'),
    image: 'https://image.tmdb.org/t/p/w1280/jQ6Vuxe1CEPMXTF7d0fZgdIBY8U.jpg',
  },
  {
    name: 'Zootopia (2016)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Амьтдын хотод туулай цагдаа болох нь — хүүхдийн кино дүрд ноцтой сэдэв',
    link: imdb('tt2948356'),
    image: 'https://image.tmdb.org/t/p/w1280/9tOkjBEiiGcaClgJFtwocStZvIT.jpg',
  },
  {
    name: 'Big Hero 6 (2014)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Хөөрхөн эмнэлгийн робот ба ах дүүгийн уй гашуу',
    link: imdb('tt2245084'),
    image: 'https://image.tmdb.org/t/p/w1280/4s2d3xdyqotiVNHTlTlJjrr3q0H.jpg',
  },
  {
    name: 'How to Train Your Dragon (2010)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Викинг хүү луутай найзлах нь — нислэгийн дүрс нь гайхалтай',
    link: imdb('tt0892769'),
    image: 'https://image.tmdb.org/t/p/w1280/59vDC1BuEQvti24OMr0ZvtAK6R1.jpg',
  },
  {
    name: 'Home Alone (1990)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Гэртээ ганцаараа үлдсэн хүү хоёр хулгайчийг тарчлаана',
    link: imdb('tt0099785'),
    image: 'https://image.tmdb.org/t/p/w1280/ih2xVgeMS8R5WUetYE8Mr9hVTlB.jpg',
  },
  {
    name: 'E.T. the Extra-Terrestrial (1982)',
    group: 'Гэр бүлээрээ үзэх',
    description: 'Спилбергийн сонгодог — хүү, харь гаригийнхан, дугуй, сар',
    link: imdb('tt0083866'),
    image: 'https://image.tmdb.org/t/p/w1280/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg',
  },
  {
    name: 'Superbad (2007)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Сургуулиа төгсөх гэж буй хоёр найзын нэг шөнийн үймээн',
    link: imdb('tt0829482'),
    image: 'https://image.tmdb.org/t/p/w1280/coru98UcFBzJIU7bxZguxaePgu0.jpg',
  },
  {
    name: 'The Hangover (2009)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Вегаст юу болсноо санахгүй байгаа гурван найз',
    link: imdb('tt1119646'),
    image: 'https://image.tmdb.org/t/p/w1280/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg',
  },
  {
    name: 'Game Night (2018)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Тоглоомын үдэш жинхэнэ хулгайд хувирсан нь — гэнэтийн ухаалаг инээдэм',
    link: imdb('tt2704998'),
    image: 'https://image.tmdb.org/t/p/w1280/aKPCZwkSZy2ASLo0QKeYmcoplfA.jpg',
  },
  {
    name: '21 Jump Street (2012)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Хоёр цагдаа сургуульд нууц ажиллагаанд явж, бүх зүйлийг сүйрүүлнэ',
    link: imdb('tt1232829'),
    image: 'https://image.tmdb.org/t/p/w1280/rXrpYOveFl76ivMmyb2612T7Q8w.jpg',
  },
  {
    name: 'Shaun of the Dead (2004)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Зомбигийн апокалипсисийг паб руу зугтаж шийдэх гэсэн англи инээдэм',
    link: imdb('tt0365748'),
    image: 'https://image.tmdb.org/t/p/w1280/wb34q3VgzHgL8frVMywrN3wXmqx.jpg',
  },
  {
    name: 'Jumanji: Welcome to the Jungle (2017)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Тоглоом дотор орчихсон дөрвөн сурагч — бүлгээрээ үзэхэд яг таарна',
    link: imdb('tt2283362'),
    image: 'https://image.tmdb.org/t/p/w1280/zZKmEmRDc7ZjFucPm2UGNgDRlDc.jpg',
  },
  {
    name: 'Deadpool (2016)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Дөрөв дэх ханыг эвдэж, харагчидтайгаа шууд ярьдаг баатар',
    link: imdb('tt1431045'),
    image: 'https://image.tmdb.org/t/p/w1280/en971MEXui9diirXlogOrPKmsEn.jpg',
  },
  {
    name: 'The Grand Budapest Hotel (2014)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Уэс Андерсоны хамгийн тэгш хэмтэй, хамгийн хөгжилтэй нь',
    link: imdb('tt2278388'),
    image: 'https://image.tmdb.org/t/p/w1280/9udCLTxTFl28RxnK8Q05E154ZGa.jpg',
  },
  {
    name: 'Knives Out (2019)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Сонгодог мөрдөгчийн оньсого, орчин үеийн хэлбэрээр',
    link: imdb('tt8946378'),
    image: 'https://image.tmdb.org/t/p/w1280/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg',
  },
  {
    name: 'Zombieland (2009)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Зомби апокалипсис, роуд трип, Билл Мюррей',
    link: imdb('tt1156398'),
    image: 'https://image.tmdb.org/t/p/w1280/oihWVx3imvRKujnGmSDYhfG1gI5.jpg',
  },
  {
    name: 'Men in Black (1997)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Хар костюмтай хоёр агент харь гаригийнхныг хариуцна',
    link: imdb('tt0119654'),
    image: 'https://image.tmdb.org/t/p/w1280/o9puyKpayQoX8ikIaYtf2PfKv3.jpg',
  },
  {
    name: 'Kingsman: The Secret Service (2015)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Англи тагнуулын элэглэл — сүмийн тулааны хэсэг нь домог болсон',
    link: imdb('tt2802144'),
    image: 'https://image.tmdb.org/t/p/w1280/qzUIOTk0E3F1zjvYjcBRTKUTgf9.jpg',
  },
  {
    name: 'Thor: Ragnarok (2017)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Marvel-ийн хамгийн инээдэмтэй нь — Тайка Вайтитигийн гар',
    link: imdb('tt3501632'),
    image: 'https://image.tmdb.org/t/p/w1280/vLmHH8jAy8Jq8uBsLucd3592WGh.jpg',
  },
  {
    name: 'Hot Fuzz (2007)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Тосгон руу шилжүүлсэн Лондонгийн загварын цагдаа',
    link: imdb('tt0425112'),
    image: 'https://image.tmdb.org/t/p/w1280/9rMSCFH9zhv1vILpEZQlUJs9iUm.jpg',
  },
  {
    name: 'Tropic Thunder (2008)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Дайны киноны зураг авалт жинхэнэ дайн болж хувирсан нь',
    link: imdb('tt0942385'),
    image: 'https://image.tmdb.org/t/p/w1280/4pLi4QMm0MZ9TSoF3l8qQmY9HNO.jpg',
  },
  {
    name: 'Pineapple Express (2008)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Санамсаргүй гэрч болчихсон хоёр залуугийн зугталт',
    link: imdb('tt0910936'),
    image: 'https://image.tmdb.org/t/p/w1280/aO6Z7ErkEoahGFKYdEs4k4ilWFe.jpg',
  },
  {
    name: "Ferris Bueller's Day Off (1986)",
    group: 'Найзуудтайгаа үзэх',
    description: 'Сургуулиа тасалсан нэг өдрийг урлаг болгосон нь',
    link: imdb('tt0091042'),
    image: 'https://image.tmdb.org/t/p/w1280/leehjwM57DKJ79XMUll4oAF0kin.jpg',
  },
  {
    name: 'The Nice Guys (2016)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Далаад оны Лос-Анжелес, хоёр чадваргүй мөрдөгч',
    link: imdb('tt3799694'),
    image: 'https://image.tmdb.org/t/p/w1280/yxYUN3fBPJdTNdXC1l8L24XFPhX.jpg',
  },
  {
    name: 'Bridesmaids (2011)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Хуримын бэлтгэл бүрэн сүйрэх нь',
    link: imdb('tt1478338'),
    image: 'https://image.tmdb.org/t/p/w1280/1pkpV7a02phSfAPeGVmpHaQd99J.jpg',
  },
  {
    name: 'Step Brothers (2008)',
    group: 'Найзуудтайгаа үзэх',
    description: 'Дөчин настай хоёр эрэгтэй ах дүү болох нь — утгагүй, гэхдээ инээдтэй',
    link: imdb('tt0838283'),
    image: 'https://image.tmdb.org/t/p/w1280/247H2jS9Te9TTmKDcAMg3LN5gmI.jpg',
  },
  {
    name: 'Titanic (1997)',
    group: 'Хамгийн алдартай',
    description: 'Тайлбар шаардахгүй. Хэрэв үзээгүй бол одоо цаг нь болсон',
    link: imdb('tt0120338'),
    image: 'https://image.tmdb.org/t/p/w1280/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg',
  },
  {
    name: 'Inception (2010)',
    group: 'Хамгийн алдартай',
    description: 'Зүүд доторх зүүд — үзэж дуусмагц маргаан эхэлнэ',
    link: imdb('tt1375666'),
    image: 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
  },
  {
    name: 'The Dark Knight (2008)',
    group: 'Хамгийн алдартай',
    description: 'Жокер. Кино түүхэн дэх хамгийн хүчтэй сөрөг дүрүүдийн нэг',
    link: imdb('tt0468569'),
    image: 'https://image.tmdb.org/t/p/w1280/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  },
  {
    name: 'Forrest Gump (1994)',
    group: 'Хамгийн алдартай',
    description: 'Нэг хүний амьдралаар дамжуулан ярьсан Америкийн хагас зууны түүх',
    link: imdb('tt0109830'),
    image: 'https://image.tmdb.org/t/p/w1280/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg',
  },
  {
    name: 'Interstellar (2014)',
    group: 'Хамгийн алдартай',
    description: 'Сансар, цаг хугацаа, эцэг охины хайр — Ноланы хамгийн сэтгэл хөдөлгөм нь',
    link: imdb('tt0816692'),
    image: 'https://image.tmdb.org/t/p/w1280/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  },
  {
    name: 'The Shawshank Redemption (1994)',
    group: 'Хамгийн алдартай',
    description: 'IMDb-ийн жагсаалтын тэргүүнд олон жил тасралтгүй сууж буй кино',
    link: imdb('tt0111161'),
    image: 'https://image.tmdb.org/t/p/w1280/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  },
  {
    name: 'Pulp Fiction (1994)',
    group: 'Хамгийн алдартай',
    description: 'Тарантиногийн холилдуулсан өгүүлэмж — киног өөрчилсөн',
    link: imdb('tt0110912'),
    image: 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  },
  {
    name: 'Fight Club (1999)',
    group: 'Хамгийн алдартай',
    description: 'Эхний дүрэм: энэ тухай битгий ярь',
    link: imdb('tt0137523'),
    image: 'https://image.tmdb.org/t/p/w1280/c6OLXfKAk5BKeR6broC8pYiCquX.jpg',
  },
  {
    name: 'The Matrix (1999)',
    group: 'Хамгийн алдартай',
    description: 'Улаан эсвэл цэнхэр эм. Сонголт таных',
    link: imdb('tt0133093'),
    image: 'https://image.tmdb.org/t/p/w1280/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg',
  },
  {
    name: 'The Godfather (1972)',
    group: 'Хамгийн алдартай',
    description: 'Кино урлагийн оргилуудын нэг. Гурван цаг ч богино санагдана',
    link: imdb('tt0068646'),
    image: 'https://image.tmdb.org/t/p/w1280/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  },
  {
    name: 'The Lord of the Rings: The Fellowship of the Ring (2001)',
    group: 'Хамгийн алдартай',
    description: 'Дундад дэлхий рүү хийх аяллын эхлэл',
    link: imdb('tt0120737'),
    image: 'https://image.tmdb.org/t/p/w1280/mWDdRXTivGE7aaY2vo1Ie0PfCX5.jpg',
  },
  {
    name: 'Parasite (2019)',
    group: 'Хамгийн алдартай',
    description: 'Оскар авсан Солонгос кино — анги давхаргын тухай хамгийн хурц',
    link: imdb('tt6751668'),
    image: 'https://image.tmdb.org/t/p/w1280/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
  },
  {
    name: 'Se7en (1995)',
    group: 'Хамгийн алдартай',
    description: 'Долоон нүгэл, хоёр мөрдөгч, мартагдахааргүй төгсгөл',
    link: imdb('tt0114369'),
    image: 'https://image.tmdb.org/t/p/w1280/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg',
  },
  {
    name: 'Gladiator (2000)',
    group: 'Хамгийн алдартай',
    description: 'Ромын жанжин боолын тулаанч болох нь',
    link: imdb('tt0172495'),
    image: 'https://image.tmdb.org/t/p/w1280/jhk6D8pim3yaByu1801kMoxXFaX.jpg',
  },
  {
    name: "Schindler's List (1993)",
    group: 'Хамгийн алдартай',
    description: 'Холокостын тухай. Хүнд, гэхдээ үзэх ёстой',
    link: imdb('tt0108052'),
    image: 'https://image.tmdb.org/t/p/w1280/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  },
  {
    name: 'The Green Mile (1999)',
    group: 'Хамгийн алдартай',
    description: 'Цаазын өрөөний харуул ба ер бусын хоригдол',
    link: imdb('tt0120689'),
    image: 'https://image.tmdb.org/t/p/w1280/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  },
  {
    name: 'Django Unchained (2012)',
    group: 'Хамгийн алдартай',
    description: 'Тарантиногийн вестерн — боолчлолын тухай өшөө авалт',
    link: imdb('tt1853728'),
    image: 'https://image.tmdb.org/t/p/w1280/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg',
  },
  {
    name: 'Joker (2019)',
    group: 'Хамгийн алдартай',
    description: 'Хотод мартагдсан хүн хэрхэн мангас болдгийг харуулсан',
    link: imdb('tt7286456'),
    image: 'https://image.tmdb.org/t/p/w1280/rlay2M5QYvi6igbGcFjq8jxeusY.jpg',
  },
  {
    name: 'Back to the Future (1985)',
    group: 'Хамгийн алдартай',
    description: 'Наяад оны хамгийн төгс адал явдал — DeLorean, наян найман миль',
    link: imdb('tt0088763'),
    image: 'https://image.tmdb.org/t/p/w1280/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg',
  },
  {
    name: 'The Silence of the Lambs (1991)',
    group: 'Хамгийн алдартай',
    description: 'Ханнибал Лектер. Оскарын бүх томоохон шагналыг авсан',
    link: imdb('tt0102926'),
    image: 'https://image.tmdb.org/t/p/w1280/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg',
  },
];

replaceSuggestCollection(COLLECTION_SLUG, MOVIES).catch((error) => { console.error(error); process.exit(1); }).finally(() => prisma.$disconnect());
